# Analyzing Anomalies with Time Series Data Using BQML

### Get Top 10 Stores based on Sales

In [2]:
%%bigquery 
SELECT store_name, SUM(sale_dollars) AS total_sales
FROM `bigquery-public-data.iowa_liquor_sales.sales`
WHERE date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH) AND CURRENT_DATE()
GROUP BY store_name
ORDER BY total_sales DESC
LIMIT 10;

Query is running:   0%|          |

Downloading:   0%|          |

                                        store_name  total_sales
0                     HY-VEE #3 / BDI / DES MOINES    793067.00
1                                   CENTRAL CITY 2    693248.59
2                           ANOTHER ROUND / DEWITT    455609.79
3  WALL TO WALL WINE AND SPIRITS / WEST DES MOINES    348965.18
4                                BENZ DISTRIBUTING    258898.00
5                      COSTCO WHOLESALE #788 / WDM    231101.33
6                     I-80 LIQUOR / COUNCIL BLUFFS    220539.98
7                         HY-VEE #7 / CEDAR RAPIDS    216959.67
8                                   WILKIE LIQUORS    202208.34
9    HY-VEE WINE AND SPIRITS #1 (1281) / IOWA CITY    191254.48

### Get Training Data and Testing Data for The Ten Stores

In [13]:
%%bigquery
CREATE TABLE `solutions-2023-mar-107.`
SELECT *
FROM `bigquery-public-data.iowa_liquor_sales.sales` a
WHERE date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH) AND CURRENT_DATE()
AND store_name IN (
    SELECT store_name
FROM `bigquery-public-data.iowa_liquor_sales.sales`
WHERE date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH) AND CURRENT_DATE()
GROUP BY store_name
ORDER BY SUM(sale_dollars) DESC
LIMIT 10)

Query is running:   0%|          |

Downloading:   0%|          |

,invoice_and_item_number,date,store_number,store_name,address,city,zip_code,store_location,county_number,county,...,item_number,item_description,pack,bottle_volume_ml,state_bottle_cost,state_bottle_retail,bottles_sold,sale_dollars,volume_sold_liters,volume_sold_gallons
0,INV-65737200016,2023-12-28,4312,I-80 LIQUOR / COUNCIL BLUFFS,2411 S 24TH ST #1 PO STN RR,COUNCIL BLUFFS,51501,POINT(-95.878348013 41.238121996),None,POTTAWATTAMIE,...,86739,OLE SMOKY APPLE PIE MOONSHINE 70PRF MINI,8,50,8.75,13.13,8,105.04,0.40,0.10
1,INV-65498900002,2023-12-20,4312,I-80 LIQUOR / COUNCIL BLUFFS,2411 S 24TH ST #1 PO STN RR,COUNCIL BLUFFS,51501,POINT(-95.878348013 41.238121996),None,POTTAWATTAMIE,...,994502,HA ORPHAN BARREL CASTLES CURSE,6,750,87.49,131.24,1,131.24,0.75,0.19
2,INV-65737200002,2023-12-28,4312,I-80 LIQUOR / COUNCIL BLUFFS,2411 S 24TH ST #1 PO STN RR,COUNCIL BLUFFS,51501,POINT(-95.878348013 41.238121996),None,POTTAWATTAMIE,...,11294,CROWN ROYAL,24,375,8.49,12.74,24,305.76,9.00,2.37
3,INV-65737300012,2023-12-28,4312,I-80 LIQUOR / COUNCIL BLUFFS,2411 S 24TH ST #1 PO STN RR,COUNCIL BLUFFS,51501,POINT(-95.878348013 41.238121996),None,POTTAWATTAMIE,...,5006,GLENFIDDICH 12YR SPECIAL RESERVE,12,750,30.00,45.00,24,1080.00,18.00,4.75
4,INV-65232800017,2023-12-13,4312,I-80 LIQUOR / COUNCIL BLUFFS,2411 S 24TH ST #1 PO STN RR,COUNCIL BLUFFS,51501,POINT(-95.878348013 41.238121996),None,POTTAWATTAMIE,...,69637,DR MCGILLICUDDYS CHERRY,12,1000,11.25,16.88,120,1980.00,120.00,31.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6676,INV-65673900034,2023-12-27,4829,CENTRAL CITY 2,1501 MICHIGAN AVE,DES MOINES,50314,POINT(-93.613286034 41.605834999),None,POLK,...,86420,REVELTON WHISKEY AND CREAM LIQUEUR,6,750,15.00,22.50,18,405.00,13.50,3.56
6677,INV-65761400014,2023-12-29,4829,CENTRAL CITY 2,1501 MICHIGAN AVE,DES MOINES,50314,POINT(-93.613286034 41.605834999),None,POLK,...,67527,KAHLUA COFFEE,12,1000,18.99,28.49,24,683.76,24.00,6.34
6678,INV-65369900043,2023-12-18,4829,CENTRAL CITY 2,1501 MICHIGAN AVE,DES MOINES,50314,POINT(-93.613286034 41.605834999),None,POLK,...,65257,JAGERMEISTER LIQUEUR,12,1000,17.42,26.13,36,940.68,36.00,9.51
6679,INV-65256000061,2023-12-14,4829,CENTRAL CITY 2,1501 MICHIGAN AVE,DES MOINES,50314,POINT(-93.613286034 41.605834999),None,POLK,...,42717,MALIBU COCONUT,12,1000,11.99,17.99,60,1079.40,60.00,15.85
6680,INV-65369900005,2023-12-18,4829,CENTRAL CITY 2,1501 MICHIGAN AVE,DES MOINES,50314,POINT(-93.613286034 41.605834999),None,POLK,...,15627,JAMESON,12,1000,20.98,31.47,120,3776.40,120.00,31.70

In [8]:
%%bigquery
SELECT store_name
FROM `bigquery-public-data.iowa_liquor_sales.sales`
WHERE date BETWEEN DATE_SUB(CURRENT_DATE(), INTERVAL 1 MONTH) AND CURRENT_DATE()
GROUP BY store_name
ORDER BY 
LIMIT 1

Query is running:   0%|          |

Downloading:   0%|          |

                  store_name
0  KIMBERLY MART / DAVENPORT